'use client'

import React, { useState, useRef, useEffect } from 'react'
import { useAuth } from '@/hooks/useAuth'
import { Card } from '@/components/ui/card'
import { Button } from '@/components/ui/button'
import { Input } from '@/components/ui/input'
import { Badge } from '@/components/ui/badge'
import { ScrollArea } from '@/components/ui/scroll-area'
import { Send, HeartPulse, FileText, AlertTriangle } from 'lucide-react'
import { ChatMessage, SourceRef } from '@/types'
import { apiService } from '@/lib/api'
import { EvidenceDrawer } from '@/components/ai/EvidenceDrawer'

export default function AIAssistantPage() {
  const { user } = useAuth()
  const [messages, setMessages] = useState<ChatMessage[]>([{
    role: 'assistant',
    content: `Hello ${user?.full_name?.split(' ')[0] || ''}, I'm your MedFlow AI Assistant. I can help answer questions based on the medical documents you've uploaded. What would you like to know?`
  }])
  const [input, setInput] = useState('')
  const [isLoading, setIsLoading] = useState(false)
  const [drawerOpen, setDrawerOpen] = useState(false)
  const [activeSources, setActiveSources] = useState<SourceRef[]>([])
  
  const scrollRef = useRef<HTMLDivElement>(null)

  useEffect(() => {
    if (scrollRef.current) {
      scrollRef.current.scrollTop = scrollRef.current.scrollHeight
    }
  }, [messages])

  const handleSend = async (e?: React.FormEvent) => {
    if (e) e.preventDefault()
    if (!input.trim() || isLoading) return

    const userMsg = input.trim()
    setInput('')
    setMessages(prev => [...prev, { role: 'user', content: userMsg }])
    setIsLoading(true)

    try {
      const res = await apiService.ai.chat(userMsg, user?.id ?? '')
      setMessages(prev => [...prev, res])
    } catch (error) {
      setMessages(prev => [...prev, { role: 'assistant', content: 'I encountered an error processing your request.' }])
    } finally {
      setIsLoading(false)
    }
  }

  const handleSourceClick = (sources: SourceRef[]) => {
    setActiveSources(sources)
    setDrawerOpen(true)
  }

  return (
    <div className="flex h-[calc(100vh-8rem)] flex-col gap-4 max-w-4xl mx-auto">
      <div className="bg-blue-50 dark:bg-blue-900/20 text-blue-800 dark:text-blue-200 p-3 rounded-md flex items-start gap-3 text-sm">
        <AlertTriangle className="h-5 w-5 shrink-0 mt-0.5" />
        <p>Responses are generated by AI based on your uploaded documents and general medical information. <strong>This does not replace professional medical judgment. Always consult your healthcare provider.</strong></p>
      </div>

      <Card className="flex-1 flex flex-col overflow-hidden">
        <ScrollArea className="flex-1 p-4" ref={scrollRef}>
          <div className="space-y-4">
            {messages.map((msg, i) => (
              <div key={i} className={`flex ${msg.role === 'user' ? 'justify-end' : 'justify-start'}`}>
                <div className={`max-w-[80%] rounded-2xl px-4 py-3 ${
                  msg.role === 'user' 
                    ? 'bg-primary text-primary-foreground rounded-br-none' 
                    : 'bg-muted rounded-bl-none'
                }`}>
                  <div className="flex items-center gap-2 mb-1 opacity-80 text-xs font-medium">
                    {msg.role === 'assistant' ? (
                      <><HeartPulse className="h-3 w-3" /> MedFlow AI</>
                    ) : 'You'}
                  </div>
                  <p className="text-sm whitespace-pre-wrap leading-relaxed">{msg.content}</p>
                  
                  {msg.sources && msg.sources.length > 0 && (
                    <div className="mt-3 pt-3 border-t border-primary-foreground/20 dark:border-border flex flex-wrap gap-2">
                      {msg.sources.map((src, idx) => (
                        <Badge 
                          key={idx} 
                          variant="secondary" 
                          className="cursor-pointer hover:bg-secondary/80 text-[10px]"
                          onClick={() => handleSourceClick([src])}
                        >
                          <FileText className="h-3 w-3 mr-1" />
                          Source: {src.document_name} {src.page ? `(Pg ${src.page})` : ''}
                        </Badge>
                      ))}
                    </div>
                  )}
                </div>
              </div>
            ))}
            {isLoading && (
              <div className="flex justify-start">
                <div className="bg-muted max-w-[80%] rounded-2xl rounded-bl-none px-4 py-3">
                  <div className="flex gap-1">
                    <span className="w-2 h-2 bg-primary/40 rounded-full animate-bounce"></span>
                    <span className="w-2 h-2 bg-primary/40 rounded-full animate-bounce delay-100"></span>
                    <span className="w-2 h-2 bg-primary/40 rounded-full animate-bounce delay-200"></span>
                  </div>
                </div>
              </div>
            )}
          </div>
        </ScrollArea>
        
        <div className="p-4 border-t bg-background">
          <form onSubmit={handleSend} className="flex gap-2">
            <Input 
              placeholder="Ask a question about your medical records..." 
              value={input}
              onChange={(e) => setInput(e.target.value)}
              className="flex-1"
            />
            <Button type="submit" disabled={isLoading || !input.trim()}>
              <Send className="h-4 w-4" />
            </Button>
          </form>
          
          <div className="flex gap-2 mt-3 overflow-x-auto pb-1 no-scrollbar">
            {['What medications am I taking?', 'Summarize my last visit', 'What are my allergies?'].map((q, i) => (
              <Badge 
                key={i} 
                variant="outline" 
                className="cursor-pointer whitespace-nowrap hover:bg-accent"
                onClick={() => setInput(q)}
              >
                {q}
              </Badge>
            ))}
          </div>
        </div>
      </Card>

      <EvidenceDrawer 
        isOpen={drawerOpen} 
        onClose={() => setDrawerOpen(false)} 
        sources={activeSources} 
      />
    </div>
  )
}
