"""
MedFlow AI — Medical Summary Agent
Generates clinical and patient-friendly summaries.
"""
from typing import Dict, List, Optional
import json
import logging

from app.config import settings

logger = logging.getLogger(__name__)

CLINICAL_SUMMARY_PROMPT = """You are a medical documentation assistant generating a clinical summary for healthcare professionals.

Generate a structured summary that includes:
- Major active diagnoses
- Current medications
- Recent significant events and lab trends
- Pending follow-ups
- AI-generated flags requiring review

IMPORTANT:
- Clearly distinguish: SOURCE FACT (from records) vs AI INTERPRETATION vs items REQUIRING PROFESSIONAL REVIEW
- Use clinical language appropriate for healthcare professionals
- Do NOT make diagnostic conclusions
- Do NOT recommend treatment changes
- Every statement must reference a source document

Return JSON:
{
  "clinical_summary": {
    "active_diagnoses": [str],
    "current_medications": [str],
    "recent_events": [str],
    "lab_trends": [str],
    "pending_follow_ups": [str],
    "ai_flags_count": int,
    "narrative": str
  },
  "source_references": [{"fact": str, "source": str}],
  "disclaimer": str
}"""

PATIENT_SUMMARY_PROMPT = """You are a health information assistant creating a patient-friendly summary.

Explain medical information in simple, non-alarming language.
Avoid medical jargon. If jargon must be used, immediately explain it in plain English.

IMPORTANT:
- Do NOT diagnose or make clinical conclusions
- Do NOT tell patients to change medications
- Do NOT use fear-inducing language
- Every interpretation must be labeled as AI interpretation, not medical advice
- Include: "Please discuss any questions with your healthcare provider."

Return JSON:
{
  "patient_summary": {
    "what_we_found": str,
    "your_medications": [str],
    "your_upcoming_tasks": [str],
    "things_to_discuss_with_doctor": [str],
    "plain_language_summary": str
  },
  "disclaimer": str
}"""


def _mock_clinical_summary(patient_data: Dict) -> Dict:
    return {
        "clinical_summary": {
            "active_diagnoses": ["Type 2 Diabetes Mellitus (E11)", "Essential Hypertension (I10)"],
            "current_medications": ["Metformin 500mg (frequency discrepancy — see flags)", "Lisinopril 10mg once daily"],
            "recent_events": ["Clinic visit Jan 10, 2026 — diabetes and hypertension review", "HbA1c 7.2% recorded (above target <7.0%)"],
            "lab_trends": ["HbA1c: 7.2% — above documented reference range of <7.0%", "Fasting glucose: 142 mg/dL — above reference 70-99 mg/dL", "Blood pressure: 138/88 mmHg — above target for diabetic patient"],
            "pending_follow_ups": ["Repeat HbA1c in 3 months (high priority)", "Endocrinology referral (medium priority)", "Follow-up appointment April 15, 2026"],
            "ai_flags_count": 2,
            "narrative": "Patient with Type 2 Diabetes Mellitus and Essential Hypertension. Most recent visit (Jan 2026) records HbA1c of 7.2% (above target) and blood pressure of 138/88 mmHg. AI review flagged a Metformin frequency discrepancy between uploaded documents — requires clinical confirmation. Two follow-up actions pending.",
        },
        "source_references": [
            {"fact": "Type 2 Diabetes diagnosis", "source": "Clinic Visit Note, Jan 10 2026"},
            {"fact": "HbA1c 7.2%", "source": "Lab Report, Jan 10 2026"},
            {"fact": "Metformin frequency discrepancy", "source": "AI Comparison: Previous Prescription vs Discharge Summary"},
        ],
        "disclaimer": "This summary was generated by MedFlow AI based on uploaded documents. It does not replace clinical judgment. All AI-flagged items require professional review.",
    }


def _mock_patient_summary(patient_data: Dict) -> Dict:
    return {
        "patient_summary": {
            "what_we_found": "Based on your uploaded medical records, we found information about two health conditions: type 2 diabetes (a condition related to blood sugar) and high blood pressure. Your most recent blood test showed your HbA1c (a 3-month average of your blood sugar level) was slightly above the target range noted in your records.",
            "your_medications": [
                "Metformin — a medication used to help manage blood sugar levels",
                "Lisinopril — a medication used to help manage blood pressure",
            ],
            "your_upcoming_tasks": [
                "Blood test (HbA1c) recommended in about 3 months",
                "Specialist appointment (endocrinologist) recommended",
                "Follow-up appointment with Dr. Johnson on April 15, 2026",
            ],
            "things_to_discuss_with_doctor": [
                "Your Metformin dosing — your records show different frequencies in different documents. Your doctor should confirm the correct dose.",
                "Your blood sugar and blood pressure readings from your last visit",
            ],
            "plain_language_summary": "Your uploaded records show you are being treated for diabetes and high blood pressure. Your most recent blood test showed your blood sugar control is slightly above the target in your records. There's also a note that the dosing of one of your medications looks different in two documents — your doctor should confirm the right amount. You have a follow-up scheduled for April 2026.",
        },
        "disclaimer": "This summary is based on information extracted from your uploaded documents by MedFlow AI. It is for informational purposes only and does not replace advice from your healthcare provider. Please discuss any questions with your doctor.",
    }


class SummaryAgent:
    """
    Generates clinical and patient-friendly summaries.
    Clearly distinguishes source facts from AI interpretations.
    """

    def __init__(self):
        self.agent_name = "SummaryAgent"

    def generate_clinical_summary(self, patient_data: Dict) -> Dict:
        if settings.is_mock_ai:
            return _mock_clinical_summary(patient_data)
        try:
            from openai import OpenAI
            client = OpenAI(api_key=settings.OPENAI_API_KEY)
            data_json = json.dumps(patient_data, indent=2)[:10000]
            response = client.chat.completions.create(
                model=settings.OPENAI_MODEL,
                messages=[
                    {"role": "system", "content": CLINICAL_SUMMARY_PROMPT},
                    {"role": "user", "content": f"Generate a clinical summary for:\n\n{data_json}"},
                ],
                response_format={"type": "json_object"},
                temperature=0.2,
            )
            return json.loads(response.choices[0].message.content)
        except Exception as e:
            logger.error(f"[{self.agent_name}] Clinical summary failed: {e}")
            return {"error": str(e)}

    def generate_patient_summary(self, patient_data: Dict) -> Dict:
        if settings.is_mock_ai:
            return _mock_patient_summary(patient_data)
        try:
            from openai import OpenAI
            client = OpenAI(api_key=settings.OPENAI_API_KEY)
            data_json = json.dumps(patient_data, indent=2)[:10000]
            response = client.chat.completions.create(
                model=settings.OPENAI_MODEL,
                messages=[
                    {"role": "system", "content": PATIENT_SUMMARY_PROMPT},
                    {"role": "user", "content": f"Generate a patient-friendly summary for:\n\n{data_json}"},
                ],
                response_format={"type": "json_object"},
                temperature=0.3,
            )
            return json.loads(response.choices[0].message.content)
        except Exception as e:
            logger.error(f"[{self.agent_name}] Patient summary failed: {e}")
            return {"error": str(e)}


summary_agent = SummaryAgent()
